import React from 'react';

  const products = [
    {
        id: 1,
        name: 'Iphone 11',
        img: "../img/iphone 11.jpg",
        price: '10.690.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 2,
        name: 'Iphone 12 64GB',
        img: "img/iPhone 12 64GB.jpg",
        price: '13.490.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 3,
        name: 'Iphone 13',
        img: "img/iPhone 13.jpg",
        price: '16.690.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 4,
        name: 'IPhone 14 Plus',
        img: "img/iPhone 14 Plus..jpg",
        price: '21.790.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 5,
        name: 'Iphone 14 Pro Max',
        img: "img/iphone 14 pro-max.jpg",
        price: '26.490.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 6,
        name: 'IPhone 14 Pro',
        img: "img/iPhone 14 Pro.jpg",
        price: '24.190.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 7,
        name: 'IPhone 14',
        img: "img/iPhone 14.jpg",
        price: '19.190.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 8,
        name: 'Iphone 15 Plus',
        img: "img/iPhone 15 Plus.jpg",
        price: '25.990.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 9,
        name: 'IPhone 15 Pro Max',
        img: "img/iPhone 15 Pro Max.jpg",
        price: '34.990.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 10,
        name: 'IPhone 15',
        img: "img/iPhone 15.jpg",
        price: '21.190.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 11,
        name: 'IPhone 15 Pro',
        img: "img/iPhone 15 Pro.jpg",
        price: '27.990.000',
        tag: ['iphone', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 12,
        name: 'IPad 9 WiFi 64GB',
        img: "img/iPad 9 WiFi 64GB.jpg",
        price: '7.990.000',
        tag: ['ipad', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 13,
        name: 'IPad Air 5 M1 Wifi 64GB',
        img: "img/iPad Air 5 M1 Wifi 64GB.jpg",
        price: '14.590.000',
        tag: ['ipad', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 14,
        name: 'IPad 10 WiFi 64GB',
        img: "img/iPad 10 WiFi 64GB.jpg",
        price: '11.390.000',
        tag: ['ipad', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 15,
        name: 'IPad Pro M1 12.9 inch WiFi 2TB (2021)',
        img: "img/iPad Pro M1 12.9 inch WiFi 2TB (2021).jpg",
        price: '54.990.000',
        tag: ['ipad', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 16,
        name: 'IPad Pro M1 11 inch WiFi Cellular 2TB (2021)',
        img: "img/iPad Pro M1 11 inch WiFi Cellular 2TB (2021).jpg",
        price: '50.990.000',
        tag: ['ipad', 'apple'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },

    {
        id: 17,
        name: 'Samsung Galaxy M34 5G',
        img: "img/samsung/samsung m34-5g.jpg",
        price: '7.690.000',
        tag: ['samsung-galaxy', 'samsung'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 18,
        name: 'Samsung Galaxy Z Flip5 5G 256GB',
        img: "img/samsung/Samsung Galaxy Z Flip5 5G 256GB.jpg",
        price: '21.990.000',
        tag: ['samsung-galaxy', 'samsung'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 19,
        name: 'Samsung Galaxy Z Flip5 5G 512GB',
        img: "img/samsung/Samsung Galaxy Z Flip5 5G 512GB.jpg",
        price: '25.990.000',
        tag: ['samsung-galaxy', 'samsung'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 20,
        name: 'Samsung Galaxy Z Fold5 5G 256GB',
        img: "img/samsung/Samsung Galaxy Z Fold5 5G 256GB.jpg",
        price: '36.990.000',
        tag: ['samsung-galaxy', 'samsung'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 21,
        name: 'Samsung Galaxy Z Fold5 5G 512GB',
        img: "img/samsung/Samsung Galaxy Z Fold5 5G 512GB.jpg",
        price: '40.990.000',
        tag: ['samsung-galaxy', 'samsung'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 22,
        name: 'Samsung Galaxy Tab A8 (2022)',
        img: "img/samsung/Samsung Galaxy Tab A8 (2022).jpg",
        price: '5.390.000',
        tag: ['ipad', 'samsung'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 23,
        name: 'Samsung Galaxy Tab A7 Lite',
        img: "img/samsung/Samsung Galaxy Tab S9 Ultra 5G.jpg",
        price: '3.390.000',
        tag: ['ipad', 'samsung'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
    {
        id: 24,
        name: 'Samsung Galaxy Tab S9 Ultra 5G',
        img: "img/samsung/Samsung Galaxy Z Fold5 5G 256GB.jpg",
        price: '25.990.000',
        tag: ['ipad', 'samsung'],
        Screen: "OLED,6.1'',Super Retina XDR",
        OS: "iOS 17",
        RearCamera: "Chính 48 MP & Phụ 12 MP",
        FrontCamera: "12MP",
        Chip: "Apple A16 Bionic",
        RAM: "6GB",
        StorageCapacity: "256 GB",
        SIM: "1 Nano SIM & 1 eSIM,Hỗ trợ 5G",
        BatterPhoneCharger: "3349 mAh, 20W"
    },
  ];



export default products;